### ISSUE TITLE
doesnt even run 

### ISSUE THREAD

**Issue by ilovefood2** [abhirooptalasila/AutoSub#10]
keeps getting 
```
Extracted audio to audio/input.wav
Splitting on silent parts in audio file
Traceback (most recent call last):
  File "./autosub/main.py", line 130, in <module>
    main()
  File "./autosub/main.py", line 112, in main
    silenceRemoval(audio_file_name)
  File "/Users/kelvin/Downloads/AutoSub-master/autosub/segmentAudio.py", line 194, in silenceRemoval
    raise Exception("Input audio file not found!")
Exception: Input audio file not found!
```

**Comment by abhirooptalasila** [comment]
Hi
Please provide more info about how you've run the script, the commands, and some setup info.
