### ISSUE TITLE
Create temporary files in temporary directories

### ISSUE THREAD

**Issue by Rillke** [abhirooptalasila/AutoSub#15]
The /audio directory is never cleaned up automatically. However, this is temporary data, and should end in a [TemporaryDirectory](https://docs.python.org/3/library/tempfile.html). Failure to clean the dir can accumulate huge amounts of uncompressed audio data as well raise issues when re-running the tool with a file carrying the same name as used before: ffmpeg prompt for override and in the end, this tool tries to feed sound data from previous runs into DeepSpeech and erroring out:

```
(sub) user@machine:~/git/AutoSub$ python3 autosub/main.py --model ~/deepspeech/de/output_graph.pbmm --scorer ~/deepspeech/de/kenlm.scorer --file ~/deepspeech/de/geteiltes_polen.wav
AutoSub v0.1

TensorFlow: v2.3.0-6-g23ad988
DeepSpeech: v0.9.3-0-gf2e9c85
2021-01-31 15:59:44.865056: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.

Input file: /home/ajcay/deepspeech/de/geteiltes_polen.wav
Guessed Channel Layout for Input Stream #0.0 : mono
File '/home/ajcay/git/AutoSub/audio/geteiltes_polen.wav' already exists. Overwrite ? [y/N] y
Extracted audio to audio/geteiltes_polen.wav
Splitting on silent parts in audio file

Running inference:
 85%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                        | 82/96 [03:23<00:27,  1.93s/it]Traceback (most recent call last):
  File "autosub/main.py", line 180, in <module>
    main()
  File "autosub/main.py", line 174, in main
    ds_process_audio(ds, audio_segment_path, file_handle)
  File "autosub/main.py", line 117, in ds_process_audio
    write_to_file(file_handle, infered_text, line_count, limits)
  File "/home/ajcay/git/AutoSub/autosub/writeToFile.py", line 18, in write_to_file
    d = str(datetime.timedelta(seconds=float(limits[0])))
ValueError: could not convert string to float: 'hoerfilm16k'
 85%|████████████████████████████████████████
```

**Comment by abhirooptalasila** [comment]
Thank you for pointing this out!
