### ISSUE TITLE
Error on installing

### ISSUE THREAD

**Issue by gabriellluz** [abhirooptalasila/AutoSub#2]
Hi my friend. I'm getting the following error when installing. I think you're missing Cython package in your requirements.

```
ERROR: Command errored out with exit status 1:
     command: /media/segundohd/app_repo/autosub_deepspeech_mozilla/AutoSub/sub/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-91ax7yu0/scikit-learn/setup.py'"'"'; __file__='"'"'/tmp/pip-install-91ax7yu0/scikit-learn/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-jddk896v/install-record.txt --single-version-externally-managed --compile --install-headers /media/segundohd/app_repo/autosub_deepspeech_mozilla/AutoSub/sub/include/site/python3.8/scikit-learn
         cwd: /tmp/pip-install-91ax7yu0/scikit-learn/
    Complete output (28 lines):
    Partial import of sklearn during the build process.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-91ax7yu0/scikit-learn/setup.py", line 290, in <module>
        setup_package()
      File "/tmp/pip-install-91ax7yu0/scikit-learn/setup.py", line 286, in setup_package
        setup(**metadata)
      File "/media/segundohd/app_repo/autosub_deepspeech_mozilla/AutoSub/sub/lib/python3.8/site-packages/numpy/distutils/core.py", line 137, in setup
        config = configuration()
      File "/tmp/pip-install-91ax7yu0/scikit-learn/setup.py", line 174, in configuration
        config.add_subpackage('sklearn')
      File "/media/segundohd/app_repo/autosub_deepspeech_mozilla/AutoSub/sub/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 1033, in add_subpackage
        config_list = self.get_subpackage(subpackage_name, subpackage_path,
      File "/media/segundohd/app_repo/autosub_deepspeech_mozilla/AutoSub/sub/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 999, in get_subpackage
        config = self._get_configuration_from_setup_py(
      File "/media/segundohd/app_repo/autosub_deepspeech_mozilla/AutoSub/sub/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 941, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "sklearn/setup.py", line 62, in configuration
        config.add_subpackage('utils')
      File "/media/segundohd/app_repo/autosub_deepspeech_mozilla/AutoSub/sub/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 1033, in add_subpackage
        config_list = self.get_subpackage(subpackage_name, subpackage_path,
      File "/media/segundohd/app_repo/autosub_deepspeech_mozilla/AutoSub/sub/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 999, in get_subpackage
        config = self._get_configuration_from_setup_py(
      File "/media/segundohd/app_repo/autosub_deepspeech_mozilla/AutoSub/sub/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 941, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "sklearn/utils/setup.py", line 8, in configuration
        from Cython import Tempita
    ModuleNotFoundError: No module named 'Cython'
    ----------------------------------------
ERROR: Command errored out with exit status 1: /media/segundohd/app_repo/autosub_deepspeech_mozilla/AutoSub/sub/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-91ax7yu0/scikit-learn/setup.py'"'"'; __file__='"'"'/tmp/pip-install-91ax7yu0/scikit-learn/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-jddk896v/install-record.txt --single-version-externally-managed --compile --install-headers /media/segundohd/app_repo/autosub_deepspeech_mozilla/AutoSub/sub/include/site/python3.8/scikit-learn Check the logs for full command output.
```

**Comment by gabriellluz** [comment]
Doing `"pip3 install cython" `solved the problem.

**Comment by lehuuhanh** [comment]
How to create Chinese and Japanese subtitles autosub

**Comment by abhirooptalasila** [comment]
Hi @lehuuhanh 
I don't think there are pre-trained Chinese/Japanese models available for DeepSpeech. Since the alphabet and language models are different, you'll need to train your own model from scratch - provided you have sufficient data. Check [this](https://discourse.mozilla.org/search?q=chinese%20category%3A247) for some previous work. 

If you plan on training from scratch, you can use the [Mozilla Common Voice Dataset](https://commonvoice.mozilla.org/en/datasets).
