### ISSUE TITLE
I dont get it 

### ISSUE THREAD

**Issue by 1sm23** [abhirooptalasila/AutoSub#4]
after runing `pip3 install -r requirements.txt`
```bash
sub) 1sm23@liushimeHacmini AutoSub % pip3 install -r requirements.txt
Requirement already satisfied: cycler==0.10.0 in ./sub/lib/python3.8/site-packages (from -r requirements.txt (line 1)) (0.10.0)
Requirement already satisfied: Cython==0.29.21 in ./sub/lib/python3.8/site-packages (from -r requirements.txt (line 2)) (0.29.21)
Collecting numpy==1.18.1
  Using cached numpy-1.18.1-cp38-cp38-macosx_10_9_x86_64.whl (15.2 MB)
Requirement already satisfied: deepspeech==0.8.2 in ./sub/lib/python3.8/site-packages (from -r requirements.txt (line 4)) (0.8.2)
Requirement already satisfied: joblib==0.16.0 in ./sub/lib/python3.8/site-packages (from -r requirements.txt (line 5)) (0.16.0)
Requirement already satisfied: kiwisolver==1.2.0 in ./sub/lib/python3.8/site-packages (from -r requirements.txt (line 6)) (1.2.0)
Requirement already satisfied: pydub==0.23.1 in ./sub/lib/python3.8/site-packages (from -r requirements.txt (line 7)) (0.23.1)
Requirement already satisfied: pyparsing==2.4.7 in ./sub/lib/python3.8/site-packages (from -r requirements.txt (line 8)) (2.4.7)
Requirement already satisfied: python-dateutil==2.8.1 in ./sub/lib/python3.8/site-packages (from -r requirements.txt (line 9)) (2.8.1)
Collecting scikit-learn==0.21.3
  Using cached scikit-learn-0.21.3.tar.gz (12.2 MB)
Requirement already satisfied: scipy==1.4.1 in ./sub/lib/python3.8/site-packages (from -r requirements.txt (line 11)) (1.4.1)
Requirement already satisfied: six==1.15.0 in ./sub/lib/python3.8/site-packages (from -r requirements.txt (line 12)) (1.15.0)
Collecting tqdm==4.44.1
  Using cached tqdm-4.44.1-py2.py3-none-any.whl (60 kB)
Using legacy 'setup.py install' for scikit-learn, since package 'wheel' is not installed.
Installing collected packages: numpy, scikit-learn, tqdm
  Attempting uninstall: numpy
    Found existing installation: numpy 1.17.3
    Uninstalling numpy-1.17.3:
      Successfully uninstalled numpy-1.17.3
    Running setup.py install for scikit-learn ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/1sm23/Documents/GitHub.nosync/AutoSub/sub/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/0c/hhcsy8ws0dv5rbfl9w3kt9940000gp/T/pip-install-xijjs7wh/scikit-learn/setup.py'"'"'; __file__='"'"'/private/var/folders/0c/hhcsy8ws0dv5rbfl9w3kt9940000gp/T/pip-install-xijjs7wh/scikit-learn/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/0c/hhcsy8ws0dv5rbfl9w3kt9940000gp/T/pip-record-tolv31lh/install-record.txt --single-version-externally-managed --compile --install-headers /Users/1sm23/Documents/GitHub.nosync/AutoSub/sub/include/site/python3.8/scikit-learn
         cwd: /private/var/folders/0c/hhcsy8ws0dv5rbfl9w3kt9940000gp/T/pip-install-xijjs7wh/scikit-learn/
    Complete output (51 lines):
    Partial import of sklearn during the build process.
    C compiler: xcrun -sdk macosx clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -iwithsysroot/System/Library/Frameworks/System.framework/PrivateHeaders -iwithsysroot/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/Headers -arch arm64 -arch x86_64
    
    compile options: '-c'
    extra options: '-fopenmp'
    xcrun: test_openmp.c
    clang: error: unsupported option '-fopenmp'
    clang: error: unsupported option '-fopenmp'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/0c/hhcsy8ws0dv5rbfl9w3kt9940000gp/T/pip-install-xijjs7wh/scikit-learn/setup.py", line 290, in <module>
        setup_package()
      File "/private/var/folders/0c/hhcsy8ws0dv5rbfl9w3kt9940000gp/T/pip-install-xijjs7wh/scikit-learn/setup.py", line 286, in setup_package
        setup(**metadata)
      File "/Users/1sm23/Documents/GitHub.nosync/AutoSub/sub/lib/python3.8/site-packages/numpy/distutils/core.py", line 137, in setup
        config = configuration()
      File "/private/var/folders/0c/hhcsy8ws0dv5rbfl9w3kt9940000gp/T/pip-install-xijjs7wh/scikit-learn/setup.py", line 174, in configuration
        config.add_subpackage('sklearn')
      File "/Users/1sm23/Documents/GitHub.nosync/AutoSub/sub/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 1033, in add_subpackage
        config_list = self.get_subpackage(subpackage_name, subpackage_path,
      File "/Users/1sm23/Documents/GitHub.nosync/AutoSub/sub/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 999, in get_subpackage
        config = self._get_configuration_from_setup_py(
      File "/Users/1sm23/Documents/GitHub.nosync/AutoSub/sub/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 941, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "sklearn/setup.py", line 76, in configuration
        maybe_cythonize_extensions(top_path, config)
      File "/private/var/folders/0c/hhcsy8ws0dv5rbfl9w3kt9940000gp/T/pip-install-xijjs7wh/scikit-learn/sklearn/_build_utils/__init__.py", line 42, in maybe_cythonize_extensions
        with_openmp = check_openmp_support()
      File "/private/var/folders/0c/hhcsy8ws0dv5rbfl9w3kt9940000gp/T/pip-install-xijjs7wh/scikit-learn/sklearn/_build_utils/openmp_helpers.py", line 140, in check_openmp_support
        raise CompileError(err_message)
    distutils.errors.CompileError:
                        ***
    
    It seems that scikit-learn cannot be built with OpenMP support.
    
    - Make sure you have followed the installation instructions:
    
        https://scikit-learn.org/dev/developers/advanced_installation.html
    
    - If your compiler supports OpenMP but the build still fails, please
      submit a bug report at:
    
        https://github.com/scikit-learn/scikit-learn/issues
    
    - If you want to build scikit-learn without OpenMP support, you can set
      the environment variable SKLEARN_NO_OPENMP and rerun the build
      command. Note however that some estimators will run in sequential
      mode and their `n_jobs` parameter will have no effect anymore.
    
                        ***
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/1sm23/Documents/GitHub.nosync/AutoSub/sub/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/0c/hhcsy8ws0dv5rbfl9w3kt9940000gp/T/pip-install-xijjs7wh/scikit-learn/setup.py'"'"'; __file__='"'"'/private/var/folders/0c/hhcsy8ws0dv5rbfl9w3kt9940000gp/T/pip-install-xijjs7wh/scikit-learn/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/0c/hhcsy8ws0dv5rbfl9w3kt9940000gp/T/pip-record-tolv31lh/install-record.txt --single-version-externally-managed --compile --install-headers /Users/1sm23/Documents/GitHub.nosync/AutoSub/sub/include/site/python3.8/scikit-learn Check the logs for full command output.
```

**Comment by abhirooptalasila** [comment]
Hi
This same issue was discussed [here](https://github.com/scikit-learn/scikit-learn/issues/14624). You can either try installing the packages individually or follow [this](https://github.com/scikit-learn/scikit-learn/issues/15742)

**Comment by 1sm23** [comment]
> Hi
> This same issue was discussed [here](https://github.com/scikit-learn/scikit-learn/issues/14624). You can either try installing the packages individually or follow [this](https://github.com/scikit-learn/scikit-learn/issues/15742)

thanks!
